pipeline:
  build:
    image: python:alpine
    pull: true
    secrets: [ jtcat_bot_token ]
    commands:
      - export jtcat_bot_token=$JTCAT_BOT_TOKEN
      - ln -s /lib /lib64
      - ln -s /lib/libc.musl-x86_64.so.1 ldd
      - apk add --update py-pip
      - pip install -r requirements.txt
      - python test.py
    #  - pyinstaller -F main.py
    #  - mv dist/main jtcat_bot
    #  - rm build/ dist/ -rf
      - tar czf jtcat_bot.tar.gz ../
  push:
    image: appleboy/drone-scp
    username: jiting
    password: $SSH_PASSWORD
    port: 22
    secrets: [ ssh_password ]
    target: /home/jiting/
    source: jtcat_bot.tar.gz
  deploy:
    image: appleboy/drone-ssh
    host: us.jtnet.xyz
    username: jiting
    password: $SSH_PASSWORD
    port: 22
    secrets: [ ssh_password ]
    script:
      - cd /home/jiting/
      - tar xzf jtcat_bot.tar.gz
      - echo $(date) >> run.txt
